# Generated by Django 2.2.7 on 2020-01-18 14:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cms', '0022_auto_20180620_1551'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactFormBaseFieldCMS',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='cmsplugin_contact_form_contactformbasefieldcms', serialize=False, to='cms.CMSPlugin')),
                ('label', models.CharField(max_length=255)),
                ('html_id', models.CharField(max_length=50)),
                ('html_name', models.CharField(max_length=50)),
                ('html_classes', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='ContactFormCMS',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='cmsplugin_contact_form_contactformcms', serialize=False, to='cms.CMSPlugin')),
                ('smtp_server', models.CharField(max_length=255)),
                ('smtp_port', models.CharField(max_length=10)),
                ('email', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('use_tls', models.BooleanField()),
                ('html_classes', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='ContactFormCheckboxFieldCMS',
            fields=[
                ('contactformbasefieldcms_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='cmsplugin_contact_form.ContactFormBaseFieldCMS')),
                ('value', models.CharField(max_length=255)),
                ('checked', models.BooleanField()),
            ],
            options={
                'abstract': False,
            },
            bases=('cmsplugin_contact_form.contactformbasefieldcms',),
        ),
        migrations.CreateModel(
            name='ContactFormEmailFieldCMS',
            fields=[
                ('contactformbasefieldcms_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='cmsplugin_contact_form.ContactFormBaseFieldCMS')),
                ('html_placeholder', models.CharField(blank=True, max_length=255)),
                ('default_value', models.CharField(blank=True, max_length=255)),
                ('required', models.BooleanField()),
            ],
            options={
                'abstract': False,
            },
            bases=('cmsplugin_contact_form.contactformbasefieldcms',),
        ),
        migrations.CreateModel(
            name='ContactFormPhoneFieldCMS',
            fields=[
                ('contactformbasefieldcms_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='cmsplugin_contact_form.ContactFormBaseFieldCMS')),
                ('html_placeholder', models.CharField(blank=True, max_length=255)),
                ('phone_pattern', models.CharField(blank=True, max_length=255)),
                ('phone_max_length', models.CharField(blank=True, max_length=4)),
                ('default_value', models.CharField(blank=True, max_length=255)),
                ('required', models.BooleanField()),
            ],
            options={
                'abstract': False,
            },
            bases=('cmsplugin_contact_form.contactformbasefieldcms',),
        ),
        migrations.CreateModel(
            name='ContactFormSubmitFieldCMS',
            fields=[
                ('contactformbasefieldcms_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='cmsplugin_contact_form.ContactFormBaseFieldCMS')),
                ('type', models.CharField(choices=[('button', 'Button'), ('input', 'Input')], max_length=255)),
            ],
            options={
                'abstract': False,
            },
            bases=('cmsplugin_contact_form.contactformbasefieldcms',),
        ),
        migrations.CreateModel(
            name='ContactFormTextAreaFieldCMS',
            fields=[
                ('contactformbasefieldcms_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='cmsplugin_contact_form.ContactFormBaseFieldCMS')),
                ('html_placeholder', models.CharField(blank=True, max_length=255)),
                ('html_rows', models.CharField(blank=True, max_length=4)),
                ('html_cols', models.CharField(blank=True, max_length=4)),
                ('default_value', models.CharField(blank=True, max_length=255)),
                ('required', models.BooleanField()),
            ],
            options={
                'abstract': False,
            },
            bases=('cmsplugin_contact_form.contactformbasefieldcms',),
        ),
        migrations.CreateModel(
            name='ContactFormTextFieldCMS',
            fields=[
                ('contactformbasefieldcms_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='cmsplugin_contact_form.ContactFormBaseFieldCMS')),
                ('html_placeholder', models.CharField(blank=True, max_length=255)),
                ('default_value', models.CharField(blank=True, max_length=255)),
                ('required', models.BooleanField()),
            ],
            options={
                'abstract': False,
            },
            bases=('cmsplugin_contact_form.contactformbasefieldcms',),
        ),
    ]
